### ISSUE TITLE
FTL ProcessRPCBlockByHeightTXs: TX cannot be parsed from block 865. Err: unable to resolve type URL /akash.provider.v1beta1.MsgCreateProvider

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-indexer#381]
FTL ProcessRPCBlockByHeightTXs: TX cannot be parsed from block 865. Err: unable to resolve type URL /akash.provider.v1beta1.MsgCreateProvider

**Comment by pharr117** [comment]
The same process described in this comment needs to happen here and in our Lens fork:

https://github.com/DefiantLabs/cosmos-tax-cli/issues/383#issuecomment-1506164709

**Comment by danbryan** [comment]
moving this to the backlog
