### ISSUE TITLE
Issue with docker-compose

### ISSUE THREAD

**Issue by masoudzr** [DefiantLabs/cosmos-indexer#74]
Hey I want to start the indexer using your docker compose
But it seems it's outdated and ends up with errors like:
` Error: unknown command "update-denoms" for "cosmos-indexer"`
and 
` Error: unknown flag: --base.index-chain`

**Comment by pharr117** [comment]
Hey @masoudzr thanks for the issue, yes the docker compose is out of date. I will get that updated for you.

**Comment by pharr117** [comment]
@masoudzr I pushed #87 that provides an improved Dockerfile and generalized docker-compose.yaml setup.

See the docs here for usage and let me know if you have any questions: https://github.com/DefiantLabs/cosmos-indexer/blob/main/docs/usage/indexing.md#docker-and-docker-compose

We are pushing out updates for documentation this week, so expect these to improve soon.
