### ISSUE TITLE
Cosmos SDK v50+ return empty RawLog and Logs array in TxEvents response

### ISSUE THREAD

**Issue by pharr117** [DefiantLabs/cosmos-indexer#94]
The application is heavily reliant on parsing out the events data on a per-message basis. This is possible because the TxEvents response used to return message events split out by message index.

Latest versions of Cosmos SDK now remove this data, preferring the TxResponse Events array. This array throws all events into a single array of events, which will need to have a reliable way to parse into their underlying message indexes.

This was found through a test on Osmosis and confirmed as intentional by this issue by the Osmosis team who pointed to the Cosmos SDK v50 update as the motivating factor from removing it from their fork: https://github.com/osmosis-labs/osmosis/issues/8028

Preliminary investigations have found that we may be able to use the msg_index attribute on the events now in order to split them up into their particular messages, see here for an example:

![image](https://github.com/DefiantLabs/cosmos-indexer/assets/24580777/dca4912a-e747-42a6-8f3e-f3aa408e5941)

**Comment by shapeshed** [comment]
Was there a deprecation notice for this? Got stung by this, breaking our indexers. Have move to events now anyway.

**Comment by pharr117** [comment]
@shapeshed I did not see a deprecation notice, it may be linked somewhere in the v24 docs but I could not find the commit. All I could find was the linked issue in Osmosis I see you responded to as well.

**Comment by shapeshed** [comment]
@pharr117 Fix is easy enough anyway and I understand the deprecation as it is duplicated data. Onwards 🚀
